name: Publish my website

on:
  push:
    branches:
      - main # Trigger on pushes to the default branch
  workflow_dispatch:        # Allow manual triggering of the workflow from the GitHub Actions interface

# Cancel previous runs if a new commit is pushed to the same PR or branch
concurrency:
  group: ${{ github.ref }}  # Group runs by the ref (branch or PR)
  cancel-in-progress: true  # Cancel any ongoing runs in the same group

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read  # Read access to repository contents
  pages: write    # Write access to GitHub Pages
  id-token: write # Write access to ID tokens

jobs:
  build_project:
    runs-on: ubuntu-latest
    # container: ghcr.io/xu-cheng/texlive-debian:20251002
    name: Build project
    steps:
      - name: Checkout project
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Set git safe.directory
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config --global --add safe.directory `pwd`
          
      # - name: Install packages
      #   run: |
      #     apt update
      #     apt install -y nodejs make git pkg-config graphviz libgraphviz-dev gcc musl-dev python3-dev

      - name: Install elan
        run: curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y

      - name: Cache
        uses: actions/cache/restore@v4
        with:
          path: |
            .lake
          key: cache-${{ hashFiles('lake-manifest.json') }}

      # - name: Get Mathlib cache
      #   run: ~/.elan/bin/lake exe cache get || true

      - name: Build blog
        run: |
          ~/.elan/bin/lake exe blog

      - name: Upload website
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy _site/ --project-name=luawebpage

      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            .lake
          key: cache-${{ hashFiles('lake-manifest.json') }}
        if: ${{ always() }}
